[package]
name = "phoenix-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
phoenix-store-cozo = { path = "../phoenix-store-cozo" }
phoenix-types = { path = "../phoenix-types" }
serde.workspace = true
serde_json.workspace = true
